//! The [`NativeId`] enum: one collision-proof identifier per native function.
//!
//! Discriminants are the serialized callable index (an out-of-range bytecode
//! index the interpreter routes to the native seam). They are explicit and
//! stable: inserting a new variant never renumbers the others, and the
//! compiler rejects any accidental duplicate.

use strum::FromRepr;

/// One native function. Discriminants are explicit so inserting a variant
/// never renumbers the others (the serialized callable index is the
/// discriminant).
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, FromRepr)]
pub enum NativeId {
    // Object
    ObjectCreate = 1000,
    ObjectGetPrototypeOf = 1001,
    ObjectDefineProperty = 1002,
    ObjectEnumerableOwnKeys = 1003,
    // Array
    ArrayPush = 1100,
    ArrayPop = 1101,
    ArrayJoin = 1102,
    ArrayIsArray = 1106,
    ArrayIterator = 1103,
    ArrayIteratorEntries = 1104,
    ArrayIteratorKeys = 1105,
    // String
    StringCharAt = 1200,
    StringSlice = 1201,
    StringConstruct = 1202,
    StringMatch = 1203,
    StringReplace = 1204,
    StringSearch = 1205,
    StringSplit = 1206,
    // Number / Math / Boolean / Error
    NumberIsNan = 1300,
    MathAbs = 1400,
    BooleanConstruct = 1500,
    ErrorCreate = 1600,
    // Eval / function / console
    Eval = 1800,
    Function = 1801,
    ConsoleLog = 1900,
    // Promise
    PromiseResolve = 1710,
    PromiseReject = 1711,
    PromiseThen = 1712,
    QueueMicrotask = 1700,
    // Map / Set
    MapConstruct = 2000,
    MapGet = 2001,
    MapSet = 2002,
    MapHas = 2003,
    MapDelete = 2004,
    MapSize = 2005,
    MapIterator = 2006,
    SetConstruct = 2100,
    SetAdd = 2101,
    SetHas = 2102,
    SetDelete = 2103,
    SetSize = 2104,
    SetIterator = 2105,
    // Iterator
    IteratorNext = 2200,
    IteratorSelf = 2204,
    // RegExp
    RegExpConstruct = 2300,
    RegExpExec = 2301,
    RegExpTest = 2302,
    RegExpToString = 2303,
    RegExpCompile = 2304,
    // Generator (interp-internal fallbacks, moved from the interp's NativeFn)
    GeneratorNext = 1910,
    GeneratorReturn = 1911,
    GeneratorThrow = 1912,
    /// Module-import hook: `import * as ns from "mod"` compiles to a call on
    /// this index, which the engine intercepts to build the namespace object
    /// (see `v12-bccompiler::model::NATIVE_IMPORT_INDEX`).
    ModuleImport = 254,
}

/// The serialized index of a native function.
impl From<NativeId> for u32 {
    #[inline]
    fn from(id: NativeId) -> u32 {
        id as u32
    }
}

/// A `u32` that does not name any [`NativeId`].
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct UnknownNativeId(pub u32);

impl std::fmt::Display for UnknownNativeId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unknown native id {}", self.0)
    }
}

impl std::error::Error for UnknownNativeId {}

/// Decodes a serialized native index back into its enum variant.
///
/// The `match` is generated by [`strum::FromRepr`], so adding a variant never
/// requires updating it by hand.
impl TryFrom<u32> for NativeId {
    type Error = UnknownNativeId;

    #[inline]
    fn try_from(index: u32) -> Result<Self, Self::Error> {
        Self::from_repr(index).ok_or(UnknownNativeId(index))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_through_the_serialized_index() {
        for id in [
            NativeId::ObjectCreate,
            NativeId::ArrayPush,
            NativeId::StringSlice,
            NativeId::MathAbs,
            NativeId::PromiseThen,
            NativeId::MapSet,
            NativeId::RegExpExec,
            NativeId::GeneratorNext,
        ] {
            let index: u32 = id.into();
            assert_eq!(NativeId::try_from(index), Ok(id), "id {id:?}");
        }
    }

    #[test]
    fn unknown_indexes_are_rejected() {
        assert!(NativeId::try_from(0).is_err());
        assert!(NativeId::try_from(999).is_err());
        assert!(NativeId::try_from(0xFFFF_FFFF).is_err());
        // A gap in the explicit discriminants is not a valid id.
        assert!(NativeId::try_from(1004).is_err());
    }
}
